name: build 

on:
  push:
    branches:
      # - "main"
      - "**"

jobs:
  build_and_deploy:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    environment: DEV

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Docker image 
        run: docker build -f docker/deploy/Dockerfile -t ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_REPO}}:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push the image to the Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:latest

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          username: ${{ secrets.SERVER_USERNAME }}
          host: ${{ secrets.SERVER_HOST }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker rm $(docker stop $(docker ps -a -q --filter ancestor=${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:latest))
            docker image prune -a -f
            docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:latest
            docker run -d -p 443:8000 --env-file .env ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}

