name: Deploying the App

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  DOCKER_REPO: ${{secrets.DOCKER_REPO}}

jobs:
  build_and_deploy:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    environment: DEV

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create an .env file
        run: |
          touch .env
          echo BASE_URL=${{ secrets.BASE_URL }} >> .env
          echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
          echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env
          echo SMTP_HOST=${{ secrets.SMTP_HOST }} >> .env
          echo SMTP_USERNAME=${{ secrets.SMTP_USERNAME }} >> .env
          echo SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }} >> .env
          echo DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }} >> .env
          echo DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }} >> .env
          echo DOCKER_REPO=${{ secrets.DOCKER_REPO }} >> .env

      - name: Start containers
        run: docker compose -f "docker-compose.yml" build postgres redis app_deploy
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push the image to the Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{secrets.DOCKER_REPO}}:latest
